[install]
is_configurable = 1
state = enabled

[ui]
is_visible = 1
label = SurveyTrace (starter)

[launcher]
author = SurveyTrace
description = Starter searches and dashboards for surveytrace.reporting.event.v1 HEC / JSON events.
version = 0.14.2

[package]
id = splunk_surveytrace
check_for_updates = 0
